version: 2.1
jobs:
  build:
    working_directory: ~/tpm
    docker:
      - image: circleci/node:19.9.0

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd ~/tpm/
            npm i
      - run:
          name: build
          command: npm run build
      - run:
          name: 'cache solc'
          command: node dist/tools/cacheSolcVersions.js true
      - run:
          name: Run Tests
          command: npm test
