import ERC20 from './ERC20.json'
import ERC721 from './ERC721.json'
import RIF from './RIF.json'
import RIFF from './RIF-FLAT.json'
import ADDRESS_LINKER from './AddressLinker.json'
import CUCKOO from './cuckoo.json'
import RESOLVER from './MultiChainResolver.json'
import REGISTRAR from './Registrar.json'
import SELF_DESTRUCT from './SelfDestruct.json'
import HW_OPTIMIZED from './helloWorld.optimized.json'
export default { ERC20, ERC721, RIF, RIFF, ADDRESS_LINKER, CUCKOO, RESOLVER, REGISTRAR, SELF_DESTRUCT, HW_OPTIMIZED }